version: "3.8"
services:
  project:
    build: .
    environment:
      BUILDKITE:
      BUILDKITE_BUILD_URL:
      BUILDKITE_JOB_ID:
      BUILDKITE_AGENT_ACCESS_TOKEN:
    volumes:
      - .:/srv
      - "/var/lib/buildkite-agent/buildkite-agent:/usr/local/bin/buildkite-agent"
